import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

function buildEmailHTML({ name, status, jobTitle, company, strengths, improvements, rankingReason, customMessage }) {
  const statusIntro = {
    accepted:    `We are pleased to inform you that your application for the <strong>${jobTitle}</strong> position at <strong>${company}</strong> has been <strong>accepted</strong>!`,
    shortlisted: `Congratulations! Your application for the <strong>${jobTitle}</strong> position at <strong>${company}</strong> has been <strong>shortlisted</strong>.`,
    interview:   `We are excited to invite you to an interview for the <strong>${jobTitle}</strong> position at <strong>${company}</strong>.`,
    rejected:    `Thank you for your interest in the <strong>${jobTitle}</strong> position at <strong>${company}</strong>. After careful evaluation, we have decided to move forward with other candidates whose profiles more closely match our current requirements.`,
    waitlisted:  `Your application for the <strong>${jobTitle}</strong> position at <strong>${company}</strong> is currently on our waitlist.`,
  };

  const strengthsHTML = strengths?.length
    ? `<div style="background:#f0fdf4;border-left:4px solid #22c55e;padding:16px;border-radius:8px;margin:20px 0">
        <p style="font-weight:600;color:#166534;margin:0 0 8px">✅ Your Strengths</p>
        <ul style="margin:0;padding-left:20px;color:#14532d">${strengths.map(s => `<li>${s}</li>`).join('')}</ul>
        ${rankingReason ? `<p style="color:#14532d;margin:8px 0 0;font-size:14px">${rankingReason}</p>` : ''}
       </div>` : '';

  const feedbackHTML = improvements?.length
    ? `<div style="background:#fefce8;border-left:4px solid #eab308;padding:16px;border-radius:8px;margin:20px 0">
        <p style="font-weight:600;color:#854d0e;margin:0 0 8px">💡 Feedback for Your Development</p>
        <ul style="margin:0;padding-left:20px;color:#713f12">${improvements.map(s => `<li>${s}</li>`).join('')}</ul>
        <p style="color:#713f12;margin:8px 0 0;font-size:13px">We encourage you to apply for future positions that match your growing skill set.</p>
       </div>` : '';

  const bodyContent = customMessage
    ? `<p>Dear <strong>${name}</strong>,</p><p>${customMessage.replace(/\n/g, '<br>')}</p>`
    : `<p>Dear <strong>${name}</strong>,</p>
       <p>${statusIntro[status] || ''}</p>
       ${['accepted', 'shortlisted', 'interview'].includes(status) ? strengthsHTML : ''}
       ${status === 'rejected' ? feedbackHTML : ''}
       ${status === 'waitlisted' ? '<p>Your qualifications are impressive and we will reach out if a position becomes available.</p>' : ''}
       <p style="margin-top:24px"><strong>Next Steps:</strong> ${
         status === 'accepted' ? 'Our team will contact you shortly to discuss onboarding.' :
         status === 'shortlisted' ? 'We will be in touch soon with further details about the selection process.' :
         status === 'interview' ? 'You will receive interview schedule details shortly.' :
         status === 'waitlisted' ? 'We will notify you if a position opens up.' :
         'Thank you for your time and interest.'
       }</p>`;

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;background:#f8f7ff">
  <div style="background:white;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1)">
    <div style="background:linear-gradient(135deg,#7c3aed,#5b21b6);padding:24px;text-align:center">
      <h1 style="color:white;margin:0;font-size:24px">⚡ QuantaHire</h1>
      <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:14px">AI-Powered Recruitment Platform</p>
    </div>
    <div style="padding:32px">
      ${bodyContent}
      <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0">
      <p style="color:#6b7280;font-size:12px;text-align:center;margin:0">
        This feedback was generated by QuantaHire's AI matching system and reviewed by the hiring team.
      </p>
    </div>
  </div>
</body></html>`;
}

async function sendEmail(to, subject, html) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "QuantaHire <onboarding@resend.dev>",
      to: ["shahadym0@gmail.com"],
      subject: `[TO: ${to}] ${subject}`,
      html,
    }),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend error: ${err}`);
  }
  return res.json();
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { applications, job_title, company, custom_messages } = await req.json();
    if (!applications?.length) return Response.json({ error: 'No applications provided' }, { status: 400 });

    const SUBJECTS = {
      accepted:    `Congratulations! Update on your application for ${job_title} at ${company}`,
      shortlisted: `Congratulations! Update on your application for ${job_title} at ${company}`,
      interview:   `You're invited to interview for ${job_title} at ${company}`,
      rejected:    `Update on your application for ${job_title}`,
      waitlisted:  `Your application for ${job_title} — Status Update`,
    };

    const results = [];
    for (const app of applications) {
      const { id, candidate_email, candidate_name, status, strengths, improvements, rag_results } = app;
      if (!status || !candidate_email) { results.push({ id, success: false, error: 'Missing status or email' }); continue; }

      const rankingReason = rag_results?.feedback || rag_results?.ranking_reason || '';
      const subject = SUBJECTS[status] || `Application Update — ${job_title}`;
      const customMessage = custom_messages?.[status] || null;

      const html = buildEmailHTML({
        name: candidate_name || 'Candidate',
        status,
        jobTitle: job_title,
        company,
        strengths: strengths || [],
        improvements: improvements || [],
        rankingReason,
        customMessage,
      });

      try {
        await sendEmail(candidate_email, subject, html);
        const timestamp = new Date().toISOString();
        await base44.asServiceRole.entities.Application.update(id, {
          status_email_sent: `[${timestamp}] Status: ${status} — Email sent to ${candidate_email}`,
        });
        results.push({ id, success: true });
      } catch (err) {
        results.push({ id, success: false, error: err.message });
      }
    }

    return Response.json({ results, total: results.length, succeeded: results.filter(r => r.success).length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});